require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
